### PR TITLE
Add rules index-referencing-column and reference-actions

### PR DESCRIPTION
**Pull request by orangain**
This PR implements rules `index-referencing-column` and `reference-actions` proposed in #341.

### CODE REVIEW

**Comment by kristiandupont** [comment]
🎉

**Comment by kristiandupont** [comment]
Do you want me to publish a version with this? Or are you building PR(s) for the other rules?

**Comment by orangain** [comment]
@kristiandupont Thank you for the merge! I will send the other PR(s) in a few days.

**Comment by kristiandupont** [comment]
Great, I'll wait a bit with releasing :-)

**Pull request merged**
